# Generated by Django 4.1 on 2022-10-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0002_remove_ticket_id_ticket_t_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tickets",
            fields=[
                ("Id", models.IntegerField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=255)),
                ("Number", models.CharField(max_length=255)),
                ("Email", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
