# Generated by Django 4.1 on 2022-10-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0003_tickets"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickets",
            name="Attended",
            field=models.CharField(default="N", max_length=255),
            preserve_default=False,
        ),
    ]
