# Generated by Django 4.1.7 on 2023-04-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0004_tickets_attended"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ticket",
        ),
        migrations.RemoveField(
            model_name="tickets",
            name="Email",
        ),
        migrations.RemoveField(
            model_name="tickets",
            name="Name",
        ),
        migrations.RemoveField(
            model_name="tickets",
            name="Number",
        ),
    ]
